package com.unilearntech.unilearntech.models;

// Generated 17 May, 2013 12:13:55 PM by Hibernate Tools 3.4.0.CR1

/**
 * Channel generated by hbm2java
 */

public class VideoEncodingStatus implements java.io.Serializable {


    public enum SyncExecutionStatus {
        RUNNING,
        QUEUED,
        IDLE
    }




}
